language: node_js
sudo: false
node_js:
- node
- '6.0'
notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: eFxDayqrkdoSgETWF0jSTtn7rnGcIx36PCZ2EOLoxbrlT1Iofe324MHJL0Bk9aL8vUmlv7bhgw1SxzJLxoviMYtvPosdQ7QgP32OZy8HETme+eGnuzJJakknigH5XOUrTkUK7mnfs2CK4JSlMmw5wL/ahchaT5ZsaTclp1spx72Qmr9Hkj34abWHGAFjPzhz7FgA1Q1DE46NvJOJ8mZsOXi2petDmFQCbtwq/2tWbkazz09XpNK0x7dYBc71OJH/hFji2Ta88ZpvZZVZN0oVcxpP8nuulTK44tarwhMJIeJMxC7y8cwFsQ3X9Mw5VqHT8hkrovcKhNNTCe9BIwUUV773v90LkWjENd6VKVuH27SwbUnRbq05Zr0ByUivYuNR0YI6nVNBigTVeCDDuNMOcHZ+3WxVk8368lEEZJa4ZJP6XJIo82LxP2TXKZlPYQ5MUuAHzjYrcpAiaCN3UZKoQTYQ4AsPgQzO2KI8axS8r3CqPy53hNobv+CNnsSg8vbuZ7LpteIqlOzVtMbpQHn3tKYPxzk2KcVwZGBHmT0/k2kl4/vD/RXnMqVlMunmxTp0In8pgq2/u0tTxRwYp8Jz0o4dwewv13jFF2kdk8P6uavPThCX23F12Y67XJOQVoFtb2Zx7ThZ80g8mG76MhDnd40MrVQtFKy0LGFhBClf6Og=
